### PR TITLE
Alter Libe Cafe name

### PR DESCRIPTION
**Pull request by ilikesymmetry**

### CODE REVIEW

**Review by young-k — APPROVED** [review]
LGTM, but are we getting these checked somehow (maybe through a Cornell Dining contact), or are we eyeballing all of this?

**Comment by ilikesymmetry** [comment]
@young-k just eyeballing, the name change is to keep it consistent with the names currently used in the app

**Comment by meganle** [comment]
we can prob cross check with whatever is on cornell dining’s website

**Review by orkosinha — APPROVED** [review]
lgtm, I think one potential way to cross check GET names with Cornell Dining is to implement some sort of fuzzy search, but given how inconsistent the names are, idt that'd work well

**Pull request merged**
