### PR TITLE
Add Black formatter

### PR DESCRIPTION
**Pull request by yuna878**
- Add [black formatter](https://github.com/psf/black) ; config in `pyproject.toml`
- `.flake8` : Delete E111 from ignore to detect indentation linting (4spaces)
- Add `# flake8: noqa` to `__init__.py` files to ignore [flake8 F401](http://flake8.pycqa.org/en/2.5.5/warnings.html) error
- Update README
- Add pre-commit hook

### CODE REVIEW

**Review by meganle — COMMENTED** [review]
@alanna-zhou You guys should prob coordinate to use the same config for Black

**Review by orkosinha — APPROVED** [review]
LGTM

**Review by meganle — COMMENTED** [review]
Can we also add the precommit hook like Manish did in the microservice?

**Comment by yuna878** [comment]
@meganle Added pre-commit hook

**Review by meganle — APPROVED** [review]
awesome

**Pull request merged**
