### PR TITLE
Clean import statements & docstrings

### PR DESCRIPTION
**Pull request by yuna878**

### CODE REVIEW

**Comment by young-k** [comment]
We should probably just run `black` over this to be consistent across our repos, and add it to `requirements.txt`?

**Review by orkosinha — APPROVED** [review]

**Comment by yuna878** [comment]
@young-k  Yes for the whitespace fixes on import statements, but Black doesn't support alphabetizing & spacing formatting on docstrings. After I merge in #127 , I'll reapply the alphabetizing & docstring changes. Does this sound good?

**Comment by yuna878** [comment]
- Kept whitespace cleaning consistent with Black formatter configs
- Alphabetized constants & import statements
- Corrected docstring indenting

**Review by meganle — APPROVED** [review]

**Review by orkosinha — APPROVED** [review]
LGTM

**Pull request merged**
