### PR TITLE
Update externalEateries.json

### PR DESCRIPTION
**Pull request by whoiswillma**
Received an email from Jana and Shelby 

> Can it be edited that we are open today until 7:30pm?
> Then, starting tomorrow, Terrace will be open 11:00am – 6:30pm, 7 days a week.

So Terrace will need to be updated after tomorrow

### CODE REVIEW

**Comment by whoiswillma** [comment]
It's frustrating that such a minor and yet routine process requires two reviewers. I agree that code should require review, but this is purely data entry. Even a few hours of incorrect data means a couple of people will be burned by Eatery, and that kind of distrust can spread. In fact I've seen and felt it spread, even among people in AppDev.

**Review by alanna-zhou — APPROVED** [review]
gg

**Comment by alanna-zhou** [comment]
> It's frustrating that such a minor and yet routine process requires two reviewers. I agree that code should require review, but this is purely data entry. Even a few hours of incorrect data means a couple of people will be burned by Eatery, and that kind of distrust can spread. In fact I've seen and felt it spread, even among people in AppDev.

i think you should just make yourself admin. then when you make actual code PRs, you can just wait for the two reviewers, but for data entry change you should just merge things in. another compromise is to only require 1 reviewer -- im quite responsive so at least i'll be able to approve

**Review by raahimenon — APPROVED** [review]

**Review by leewang-codes — APPROVED** [review]

**Comment by leewang-codes** [comment]
since transit + eatery are in maintenance now, i've changed the number of required reviewers to 1 for those repos - hopefully this will help the response time

**Comment by whoiswillma** [comment]
How often does the backend update its Eateries?

**Comment by aliciaxw** [comment]
> How often does the backend update its Eateries?

i think every day? `UPDATE_DELAY = 86400`

**Comment by leewang-codes** [comment]
> How often does the backend update its Eateries?

@whoiswillma the cron job runs every day at 9am, 3pm, and 9pm

**Pull request merged**
