### PR TITLE
Make swipe dates ISO 8601

### PR DESCRIPTION
**Pull request by orkosinha**
Change date format from `HH:MM` to `yyyy-mm-dd:HH:MM:PM`, as the current Android app relies on this format.

### CODE REVIEW

**Review by young-k — COMMENTED** [review]
Will this break functionality on iOS?

**Comment by orkosinha** [comment]
Either iOS or Android needs to change how they want to handle swipe data dates

**Comment by orkosinha** [comment]
> Will this break functionality on iOS?
iOS doesn’t make any swipe related queries yet, so it should be good.

**Comment by orkosinha** [comment]
> Will this break functionality on iOS?


I found out later that iOS doesn't use swipe data at all right now, so nothing should change @young-k

**Review by meganle — APPROVED** [review]
If nothing breaks, then cool

**Review by yuna878 — APPROVED** [review]

**Pull request merged**
